
let images=[
    {
        url:[
            './assets/images/slide1.jpg',
            './assets/images/slide1-v2.jpg',
            './assets/images/slide1-v3.jpg'
        ],
        alt:'slide1'
    },
    {
        url:[
            './assets/images/slide2.jpg',
            './assets/images/slide2-v2.jpg',
            './assets/images/slide2-v3.jpg'
        ],
        alt:'slide2'
    },
    {
        url:[
            './assets/images/slide3.jpg',
            './assets/images/slide3-v2.jpg',
            './assets/images/slide3-v3.jpg'
        ],
        alt:'slide3'
    },
    {
        url:[
            './assets/images/slide4.jpg',
            './assets/images/slide4-v2.jpg',
            './assets/images/slide4-v3.jpg'
        ],
        alt:'slide4'
    },
    {
        url:[
            './assets/images/slide5.jpg',
            './assets/images/slide5-v2.jpg',
            './assets/images/slide5-v3.jpg'
        ],
        alt:'slide5'
    },
    {
        url:[
            './assets/images/slide6.jpg',
            './assets/images/slide6-v2.jpg',
            './assets/images/slide6-v3.jpg'
        ],
        alt:'slide6'
    },
    {
        url:[
            './assets/images/slide7.jpg',
            './assets/images/slide7-v2.jpg',
            './assets/images/slide7-v3.jpg'
        ],
        alt:'slide7'
    },
]
export default images;

export let latestNews=[
    {
        product:'Mouse ASUS ROG Gladius II Wireless RGB',
        price:17600,
        url:'./assets/images/latest-new1.jpg',
        alt:'product1',
    },
    {
        product:'Mother ASUS PRIME A520M-K AM4',
        price:15100,
        url:'./assets/images/latest-new2.jpg',
        alt:'product2',
    },
    {
        product:'Placa Video ASUS GeForce GTX 1660 TI 6GB GDDR6 TUF EVO OC',
        price:92450,
        url:'./assets/images/latest-new3.jpg',
        alt:'product3',
    },
    {
        product:'Mother ASUS Prime B660M-A D4',
        price:28900,
        url:'./assets/images/latest-new4.jpg',
        alt:'product4',
    },
    {
        product:'Mother ASUS Prime Z690-P WIFI S1700',
        price:59750,
        url:'./assets/images/latest-new5.jpg',
        alt:'product5',
    },
    {
        product:'Mother ASUS Prime Z690-P WIFI S1700',
        price:59750,
        url:'./assets/images/latest-new5.jpg',
        alt:'product5',
    },
    {
        product:'Mother ASUS Prime Z690-P WIFI S1700',
        price:59750,
        url:'./assets/images/latest-new5.jpg',
        alt:'product5',
    },
    {
        product:'Mother ASUS Prime Z690-P WIFI S1700',
        price:59750,
        url:'./assets/images/latest-new5.jpg',
        alt:'product5',
    },
    {
        product:'Mother ASUS Prime Z690-P WIFI S1700',
        price:59750,
        url:'./assets/images/latest-new5.jpg',
        alt:'product5',
    },
    {
        product:'Mother ASUS Prime Z690-P WIFI S1700',
        price:59750,
        url:'./assets/images/latest-new5.jpg',
        alt:'product5',
    }
]

export let brands=[
    {
        brand:'./assets/images/marca-slide-1.jpg',
        alt:'republic-of-gamers',
    },
    {
        brand:'./assets/images/marca-slide-2.jpg',
        alt:'asrock',
    },
    {
        brand:'./assets/images/marca-slide-3.jpg',
        alt:'adata',
    },
    {
        brand:'./assets/images/marca-slide-4.jpg',
        alt:'amd',
    },
    {
        brand:'./assets/images/marca-slide-5.jpg',
        alt:'zota-gaming',
    },
    {
        brand:'./assets/images/marca-slide-6.jpg',
        alt:'western-digital',
    },
    {
        brand:'./assets/images/marca-slide-7.jpg',
        alt:'view-sonic',
    },
    {
        brand:'./assets/images/marca-slide-8.jpg',
        alt:'t-force',
    },
    {
        brand:'./assets/images/marca-slide-9.jpg',
        alt:'deepcool',
    },
    {
        brand:'./assets/images/marca-slide-10.jpg',
        alt:'viper',
    },
    {
        brand:'./assets/images/marca-slide-11.jpg',
        alt:'nvidia',
    },
    {
        brand:'./assets/images/marca-slide-12.jpg',
        alt:'lian',
    },
    {
        brand:'./assets/images/marca-slide-13.jpg',
        alt:'kolink',
    },
    {
        brand:'./assets/images/marca-slide-14.jpg',
        alt:'intel',
    },
    {
        brand:'./assets/images/marca-slide-15.jpg',
        alt:'hyperx',
    },
    {
        brand:'./assets/images/marca-slide-16.jpg',
        alt:'geil',
    },
    {
        brand:'./assets/images/marca-slide-17.jpg',
        alt:'be-quiet',
    },
]