
let images=[
    {
        url:[
            './assets/images/slide1.jpg',
            './assets/images/slide1-v2.jpg',
            './assets/images/slide1-v3.jpg'
        ],
        alt:'slide1'
    },
    {
        url:[
            './assets/images/slide2.jpg',
            './assets/images/slide2-v2.jpg',
            './assets/images/slide2-v3.jpg'
        ],
        alt:'slide2'
    },
    {
        url:[
            './assets/images/slide3.jpg',
            './assets/images/slide3-v2.jpg',
            './assets/images/slide3-v3.jpg'
        ],
        alt:'slide3'
    },
    {
        url:[
            './assets/images/slide4.jpg',
            './assets/images/slide4-v2.jpg',
            './assets/images/slide4-v3.jpg'
        ],
        alt:'slide4'
    },
    {
        url:[
            './assets/images/slide5.jpg',
            './assets/images/slide5-v2.jpg',
            './assets/images/slide5-v3.jpg'
        ],
        alt:'slide5'
    },
    {
        url:[
            './assets/images/slide6.jpg',
            './assets/images/slide6-v2.jpg',
            './assets/images/slide6-v3.jpg'
        ],
        alt:'slide6'
    },
    {
        url:[
            './assets/images/slide7.jpg',
            './assets/images/slide7-v2.jpg',
            './assets/images/slide7-v3.jpg'
        ],
        alt:'slide7'
    },
]
export default images;